# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

platform :android do
  desc "自动生成 Google Play 截图"
  lane :screenshots do
    screengrab(
      app_package_name: "jlsimport.app",
      locales: ["en-US", "zh-CN"],
      clear_previous_screenshots: true,
      use_adb_root: false
    )
  end
end

lane :firebase_screenshots do
  screengrab(
    app_package_name: "com.example.myapp",
    locales: ["en-US", "zh-CN"],
    clear_previous_screenshots: true,
    use_adb_root: false,
    firebase_test_lab: true # 使用 Firebase 设备
  )
end
