export interface Iproduct {
    BarreCode?: string,
    CategoryId: number,
    CategoryLabel: string,
    Code: string,
    Color?: string,
    DefaultPhotoPath?: string,
    Label?: string,
    MainCategoryLabel?: string,
    Material?: string,
    Forme?: string,
    PreviousPrice?: number,
    Price?: number,
    ProductId: number,
    QuantityPerBox: number,
    ReferenceId: number,
    SecondCategoryLabel?: string,
    Size?: string,
    Validity: boolean
}
